name: Production Deploy

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          RANDOM_SEED: ${{ secrets.RANDOM_SEED }}
          VITE_ROOT_URL: https://d3i0k8ieonilzl.cloudfront.net
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
          MEETUP_API_BASE_URL: ${{ secrets.MEETUP_API_BASE_URL }}
          PERMISSION_BOUNDARY_ARN: ${{ secrets.PERMISSION_BOUNDARY_ARN }}
          STAGE: production
          SETTINGS_BASE_URL: ${{ secrets.SETTINGS_BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          GH_API_BASE_URL: ${{ secrets.GH_API_BASE_URL }}
          GH_AUTH_KEY: ${{ secrets.GH_AUTH_KEY }}
          EMAIL_APP_URL: ${{ secrets.EMAIL_APP_URL }}
